/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

/**
 *
 * @author nguye
 */
public class VayTienJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyNguoiHocJDialog
     */
    public VayTienJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoGioiTinh = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDiachi = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        tabs = new javax.swing.JTabbedPane();
        PnlVayTien = new javax.swing.JPanel();
        lblMaVay = new javax.swing.JLabel();
        lblMaKH = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        lblSotien = new javax.swing.JLabel();
        txtSotien = new javax.swing.JTextField();
        lblLaiSuat = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVayTien = new javax.swing.JTable();
        lblKyHan = new javax.swing.JLabel();
        cboKyHan = new javax.swing.JComboBox<>();
        txtLaiSuat = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JLabel();
        txtMaVay = new javax.swing.JLabel();
        PnlTraGop = new javax.swing.JPanel();
        lblMatra = new javax.swing.JLabel();
        lblMaVay1 = new javax.swing.JLabel();
        lblSoTienTra = new javax.swing.JLabel();
        txtSoTienTra = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtMaTra = new javax.swing.JLabel();
        txtMaVay2 = new javax.swing.JLabel();

        txtDiachi.setColumns(20);
        txtDiachi.setRows(5);
        jScrollPane3.setViewportView(txtDiachi);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys - Quản lý người học");

        lblMaVay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaVay.setText("Mã vay:");

        lblMaKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaKH.setText("Mã khách hàng:");

        btnAccept.setText("Xác nhận");

        lblSotien.setText("Số tiền cần vay:");

        lblLaiSuat.setText("Lãi suất:");

        btnHuy.setText("Huỷ bỏ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        tblVayTien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã vay", "Mã KH", "Số tiền vay", "Lãi suất", "Kỳ hạn", "Ngày vay", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tblVayTien);

        lblKyHan.setText("Kỳ hạn:");

        txtLaiSuat.setText("0.0");

        txtMaKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaKH.setText("0");

        txtMaVay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaVay.setText("0");

        javax.swing.GroupLayout PnlVayTienLayout = new javax.swing.GroupLayout(PnlVayTien);
        PnlVayTien.setLayout(PnlVayTienLayout);
        PnlVayTienLayout.setHorizontalGroup(
            PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVayTienLayout.createSequentialGroup()
                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlVayTienLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlVayTienLayout.createSequentialGroup()
                                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSotien)
                                    .addComponent(lblKyHan)
                                    .addComponent(lblLaiSuat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLaiSuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSotien)
                                        .addComponent(cboKyHan, 0, 350, Short.MAX_VALUE))))
                            .addGroup(PnlVayTienLayout.createSequentialGroup()
                                .addComponent(lblMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlVayTienLayout.createSequentialGroup()
                                .addComponent(lblMaVay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaVay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(PnlVayTienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                    .addGroup(PnlVayTienLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAccept)
                        .addGap(52, 52, 52)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)))
                .addContainerGap())
        );
        PnlVayTienLayout.setVerticalGroup(
            PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVayTienLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaVay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaVay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaKH)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSotien)
                    .addComponent(txtSotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLaiSuat)
                    .addComponent(txtLaiSuat))
                .addGap(12, 12, 12)
                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKyHan)
                    .addComponent(cboKyHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlVayTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        tabs.addTab("Vay Tiền", PnlVayTien);

        lblMatra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMatra.setText("Mã trả:");

        lblMaVay1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaVay1.setText("Mã vay:");

        lblSoTienTra.setText("Số tiền trả:");

        btnXacNhan.setText("Xác nhận");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã trả", "Mã vay", "Số tiền trả", "Ngày trả", "Trạng thái"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        txtMaTra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaTra.setText("0");

        txtMaVay2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMaVay2.setText("0");

        javax.swing.GroupLayout PnlTraGopLayout = new javax.swing.GroupLayout(PnlTraGop);
        PnlTraGop.setLayout(PnlTraGopLayout);
        PnlTraGopLayout.setHorizontalGroup(
            PnlTraGopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTraGopLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PnlTraGopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlTraGopLayout.createSequentialGroup()
                        .addComponent(lblSoTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnlTraGopLayout.createSequentialGroup()
                        .addGroup(PnlTraGopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlTraGopLayout.createSequentialGroup()
                                .addComponent(lblMaVay1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaVay2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlTraGopLayout.createSequentialGroup()
                                .addComponent(lblMatra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaTra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(421, Short.MAX_VALUE))))
            .addGroup(PnlTraGopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        PnlTraGopLayout.setVerticalGroup(
            PnlTraGopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlTraGopLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PnlTraGopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatra)
                    .addComponent(txtMaTra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlTraGopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaVay1)
                    .addComponent(txtMaVay2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlTraGopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoTienTra)
                    .addComponent(txtSoTienTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacNhan))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        tabs.addTab("Trả Góp", PnlTraGop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VayTienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VayTienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VayTienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VayTienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VayTienJDialog dialog = new VayTienJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlTraGop;
    private javax.swing.JPanel PnlVayTien;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cboKyHan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblKyHan;
    private javax.swing.JLabel lblLaiSuat;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblMaVay;
    private javax.swing.JLabel lblMaVay1;
    private javax.swing.JLabel lblMatra;
    private javax.swing.JLabel lblSoTienTra;
    private javax.swing.JLabel lblSotien;
    private javax.swing.ButtonGroup rdoGioiTinh;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblVayTien;
    private javax.swing.JTextArea txtDiachi;
    private javax.swing.JLabel txtLaiSuat;
    private javax.swing.JLabel txtMaKH;
    private javax.swing.JLabel txtMaTra;
    private javax.swing.JLabel txtMaVay;
    private javax.swing.JLabel txtMaVay2;
    private javax.swing.JTextField txtSoTienTra;
    private javax.swing.JTextField txtSotien;
    // End of variables declaration//GEN-END:variables

    
    void init() {
        this.setLocationRelativeTo(null);
    }
    
    public void selectTab(int index){
        tabs.setSelectedIndex(index);
    }
}
